In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------- ----------------------------- 3.1/12.4 MB 21.8 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.4 MB 27.3 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 26.1 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 23.0 MB/s  0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [39]:
# Numpy arrays are coded in C, so it is basically fast, memory efficiant compared to python list n.
a1=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2=np.array([[1, 2, 3], [4, 5, 6],[10,11,12]])
sumarr = a1 + a2
#Element wise multiplication
productarr = a1*a2
#Dot product of two arrays
dotProdArr = np.dot(a1,a2)
print(f"dotProdArr:: {dotProdArr}")
diffarr = a2-2
print(f"sumarr:: {sumarr}")
print(f"productarr:: {productarr}")
print(f"diffarr:: {diffarr}")

dotProdArr:: [[ 39  45  51]
 [ 84  99 114]
 [129 153 177]]
sumarr:: [[ 2  4  6]
 [ 8 10 12]
 [17 19 21]]
productarr:: [[  1   4   9]
 [ 16  25  36]
 [ 70  88 108]]
diffarr:: [[-1  0  1]
 [ 2  3  4]
 [ 8  9 10]]


## Built In functions of NumPy
Arrays are homogeneous - all elements will be of same data type, but python lists are hetrogeneous
1. Creation of array with zeros - np.zeros(rows,column) - this will create an array of 0 with specified rows and columns
2. Creation of array with same values - np.full((array shape),fill_value)

In [35]:
#2D array
np2DArray = np.zeros((3,5))
# print(f"np2DArray:: {np2DArray}")
# print(f"np2DArray shape:: {np2DArray.shape}")

#3D array
np3DArray = np.zeros((3,5,4))
# print(f"npArray:: {np3DArray}")
# print(f"np3DArray shape:: {np3DArray.shape}")

#4D array
np4DArray = np.zeros((3,5,4,3))
#print(f"np4DArray:: {np4DArray}")
print(f"np4DArray shape:: {np4DArray.shape}")

npdynamicArray = np.full((2,3,5),5)
print(f"npdynamicArray:: {npdynamicArray}")
print(f"npdynamicArray datatype:: {npdynamicArray.dtype}")
print(f"reshaped array:: {npdynamicArray.reshape(6,5)}")


npdtypeArray = np.full((2,3,5),5,dtype='<U6')
print(f"npdtypeArray:: {npdtypeArray}")
print(f"npdtypeArray datatype:: {npdtypeArray.dtype}")

#Arrange in numpy will create an array with certain conmditions
#Syntax: np.arrange(strart,stop,step)

arrangeArr = np.arange(5,20,5)
print(f"arrangeArr:: {arrangeArr}")

np4DArray shape:: (3, 5, 4, 3)
npdynamicArray:: [[[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]]
npdynamicArray datatype:: int64
reshaped array:: [[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
npdtypeArray:: [[['5' '5' '5' '5' '5']
  ['5' '5' '5' '5' '5']
  ['5' '5' '5' '5' '5']]

 [['5' '5' '5' '5' '5']
  ['5' '5' '5' '5' '5']
  ['5' '5' '5' '5' '5']]]
npdtypeArray datatype:: <U6
arrangeArr:: [ 5 10 15]


In [40]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
#15
print(arr.sum())
#15 (method syntax)
print(np.mean(arr))
#3.0
print(np.std(arr))
#1.4142135623730951 (standard deviation)
print(np.var(arr))
#2.0 (variance)
print(np.min(arr))
#1
print(np.max(arr))
#5
print(np.argmin(arr))
#0 (index of minimum)
print(np.argmax(arr))
#4 (index of maximum)

15
15
3.0
1.4142135623730951
2.0
1
5
0
4


In [42]:
#axis=0 --> Operation along the columns
#axis=1 --> operation along the row.

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.sum())
#21 (sum of all elements)
print(arr_2d.sum(axis=0))
#[579] (sum along column sums)
print(arr_2d.sum(axis=1))
#[615] (sum along row sums)
print(arr_2d.mean(axis=0))
# [2.5 3.5 4.5]
print(arr_2d.max(axis=1))
# [36]

21
[5 7 9]
[ 6 15]
[2.5 3.5 4.5]
[3 6]


## reshaping
1. Reshaping is changing the dimentions of my array, into something else, so that it fits my input. We can chnage the dimension such that the product of of dimensions given is equal to the total elements in my existing array.
2. know my one dimension is 4, but i dont wantt o calculate the second dimension, in such situations i can use -1. This -1 can be specisied for only one unkown dimension.

In [54]:
simpleArr = np.arange(50)
print(f"simpleArr:: {simpleArr}")
reshapeArr = simpleArr.reshape(5,-1)
print(f"reshaped Array:: {reshapeArr}")
#flatten - convert any dimension array to 1-D array
print(f"flattened Array:: {reshapeArr.flatten()}")
#ravel - convert any dimension array to 1-D array. Same as flatten but faster.
print(f"Raveled Array:: {reshapeArr.ravel()}")
#convert any dimension array to 1-D array w/o using ravel and flatten
print(f"reshapind 2D to 1D Array:: {reshapeArr.reshape(-1
                                             )}")

simpleArr:: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
reshaped Array:: [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
flattened Array:: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Raveled Array:: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
reshapind 2D to 1D Array:: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [64]:
simpleArray = np.array([[23,24,6,7],[56,77,987,867]])
print(f"simpleArray:: {simpleArray}")
tranposedArr = simpleArray.T
print(f"tranposedArr:: {tranposedArr}")

simpleArray:: [[ 23  24   6   7]
 [ 56  77 987 867]]
tranposedArr:: [[ 23  56]
 [ 24  77]
 [  6 987]
 [  7 867]]


In [59]:
#Comparing Python lists and numpy arrays in terms of time.
# Create large data
import time 

size =  1000000
python_list = list(range(size))
numpy_array = np.arange(size)
# Test 1: Summing elements
# Python list
start = time.time()
total = sum(python_list)
python_time = time.time() - start
#NumPy array
start = time.time()
total = np.sum(numpy_array)
numpy_time = time.time()- start
print(f"Python list sum: {python_time:.5f} seconds")
print(f"NumPy array sum: {numpy_time:.5f} seconds")
print(f"NumPy is {python_time/numpy_time:.1f} x faster")

Python list sum: 0.01198 seconds
NumPy array sum: 0.00136 seconds
NumPy is 8.8 x faster


## hstack and vstack
1. Stack is known as joining arrays together
2. hstack - joining arrays horizontally. The no.of rws will be same
3. vstack - joining arrays vertically. No.of columns will bne same

In [70]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,0])
print(f"hstack::: {np.hstack((a,b))}")
print(f"vstack::: {np.vstack((a,b))}")

c = np.array([[1,2],[3,4]])
d = np.array([[6,7],[8,9]])
print(f"hstack::: {np.hstack((c,d))}")
print(f"vstack::: {np.vstack((c,d))}")

hstack::: [1 2 3 4 5 6 7 8 9 0]
vstack::: [[1 2 3 4 5]
 [6 7 8 9 0]]
hstack::: [[1 2 6 7]
 [3 4 8 9]]
vstack::: [[1 2]
 [3 4]
 [6 7]
 [8 9]]
